# gotestsum configuration for Leaf project
# Run with: gotestsum
# https://github.com/gotestyourself/gotestsum

# Default format (already has emojis built-in)
# Available formats:
#   - pkgname-and-test-fails (✓/✗ icons, shows failures)
#   - testname (✓/✗ icons, all tests)
#   - standard-verbose (detailed output)
#   - dots (. for pass, x for fail)
format: pkgname-and-test-fails

# Packages to test
packages: ./...
